apiVersion: v1
kind: Service
metadata:
  name: nginx-sidecar-svc
spec:
  selector:
    app: nginx-sidecar
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      # nodePort omitted to allow Kubernetes to choose or set a port 30000-32767
